. ~/bin/dotfiles/vim/vimrc
. ~/bin/dotfiles/docker/docker
. ~/bin/dotfiles/docker/docker_compose
. ~/bin/dotfiles/docker/docker_install
. ~/bin/dotfiles/git/git
. ~/bin/dotfiles/linux/ibraransari
. ~/bin/dotfiles/linux/linux
. ~/bin/dotfiles/linux/colours
. ~/bin/dotfiles/linux/env
. ~/bin/dotfiles/linux/firewall
. ~/bin/dotfiles/linux/install
. ~/bin/dotfiles/linux/permission
. ~/bin/dotfiles/linux/sshserver
. ~/bin/dotfiles/linux/systeminfo
. ~/bin/dotfiles/linux/trash
. ~/bin/dotfiles/proxmox/proxmox
. ~/bin/dotfiles/linux/bashcompletion
. ~/bin/dotfiles/kubernetes/kubernetes
. ~/bin/dotfiles/ansible/ansible
. ~/bin/dotfiles/terraform/terraform
. ~/bin/dotfiles/htop/htop
. ~/bin/dotfiles/grc/grc
. ~/bin/dotfiles/nginx/nginx
. ~/bin/dotfiles/pm2/pm2