#!/bin/bash
#set -xv

NOCOLOR='\e[0m'
BOLD='\e[1m'
BLINK='\e[5m'
Blue='\e[44m'
GREEN='\e[0;32m'

# clear >$(tty)
clear >/dev/tty

echo -e " ${GREEN}${BOLD}#=========================================================#${NOCOLOR}"
echo -e " ${GREEN}${BOLD}#        Dotfiles installation is in progress....         #${NOCOLOR}"
echo -e " ${GREEN}${BOLD}#=========================================================#${NOCOLOR}"
echo '
 ____        _    __ _ _           
|  _ \  ___ | |_ / _(_) | ___  ___ 
| | | |/ _ \| __| |_| | |/ _ \/ __|
| |_| | (_) | |_|  _| | |  __/\__ \
|____/ \___/ \__|_| |_|_|\___||___/
'

# Set current dir
current_dir=$(pwd)

# Check if the directory is empty (no files or directories inside)
dotfiles_dir="$HOME/bin/dotfiles"
# Check if the directory exists
if [ ! -d "$dotfiles_dir" ]; then
    # Directory does not exist, create it and clone the repository
    mkdir -p "$dotfiles_dir"
    git clone https://github.com/meibraransari/dotfiles.git "$dotfiles_dir" &> /dev/null
else
    echo "Dotfiles is already installed."
    echo ""
    echo "Skipping installation and updating to the latest"
    echo ""
    # Update dot files
    cd ~/bin/dotfiles && git pull && cd "$current_dir" && source ~/.bash_profile
    exit 0
fi

# Install GRC
function install_grc {
    #!/bin/bash
    # Check if grc is installed
    if ! command -v grc &> /dev/null
    then
        #clear >$(tty)
        echo "Grc is not installed. Installing..."
        sudo apt-get update -y #>/dev/null 2>&1
        sudo apt-get install grc -y #>/dev/null 2>&1
        sudo sed -i 's/GRC_ALIASES=false/GRC_ALIASES=true/g' /etc/default/grc #>/dev/null 2>&1
        [ -f /etc/default/grc ] && . /etc/default/grc
        [[ -s "/etc/profile.d/grc.sh" ]] && source /etc/profile.d/grc.sh
        echo "grc installed successfully."
    else
        #clear >$(tty)
        echo "Grc is already installed."
    fi
}
install_grc

# Check if the line '. ~/bin/dotfiles/bashrc' exists in ~/.bashrc, if not, append it
if ! grep -qxF '. ~/bin/dotfiles/bashrc' ~/.bashrc; then
    echo '. ~/bin/dotfiles/bashrc 2>/dev/null' >> ~/.bashrc
fi

# Check if the line '[ -f ~/.bashrc ] && source ~/.bashrc' exists in ~/.bash_profile, if not, append it
if ! grep -qxF '[ -f ~/.bashrc ] && source ~/.bashrc' ~/.bash_profile; then
    echo '[ -f ~/.bashrc ] && source ~/.bashrc' >> ~/.bash_profile
fi

# Source ~/.bash_profile to apply changes
source ~/.bash_profile

# Check Deployment status
if [ $? -eq 0 ]
then
    #echo -e " ${GREEN}${BOLD}#=========================================================#${NOCOLOR}"
    echo -e " ${Blue}${BLINK}${BOLD}   Installation done successfully...${NOCOLOR}"
echo ""

echo -e " ${GREEN}${BOLD}-:Thanks for using Dotfiles:-		${NOCOLOR}"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""    
else
    echo "Installation Failed.. Please contact to Ibrar Ansari"
    exit 1
fi

# Change directory
cd "$current_dir"