#!/bin/bash

# Exit on error
set -e

# Update package lists
echo "Updating package lists..."
sudo apt-get update -y

# Install zsh and Git if not already installed
echo "Installing zsh and git..."
sudo apt-get install -y zsh git

# Install Oh My Zsh non-interactively
echo "Installing Oh My Zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install zsh-autosuggestions plugin
echo "Installing zsh-autosuggestions..."
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting

# Enable zsh-autosuggestions plugin
echo "Configuring zsh-autosuggestions..."
sed -i 's/^plugins=(.*)/plugins=(git cp colored-man-pages colorize zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc

# Change Theme
sed -i 's/^ZSH_THEME="[^"]*"/ZSH_THEME="agnoster"/' ~/.zshrc

# Set Dotfiles
echo '. ~/bin/dotfiles/bashrc 2>/dev/null' >> ~/.zshrc
source ~/.zshrc

# Change default shell to zsh
echo "Changing default shell to zsh..."
sudo usermod --shell $(which zsh) $USER

# Inform user to switch to zsh
echo "To complete the setup, you need to log out and log back in, or restart your terminal."

echo "Installation complete."




### Useful Links and Sources
### This article was made with the help of TheLedger.
# Oh-My-Zsh: http://ohmyz.sh/
# Plugins: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins
# Themes: https://github.com/robbyrussell/oh-my-zsh/tree/master/themes/
# Git plugin with all aliases: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git
# Customizing your shell prompt: http://www.nparikh.org/unix/prompt.php#zsh
# ArchWiki about Zsh: https://wiki.archlinux.org/index.php/zsh#Autostart_X_at_login
# Zsh syntax highlighting plugin: https://github.com/zsh-users/zsh-syntax-highlighting
# Zsh autosuggestions plugin: https://github.com/zsh-users/zsh-autosuggestions
# RobbyRussell Wiki about customization of Zsh: https://github.com/robbyrussell/oh-my-zsh/wiki/Customization
