#!/bin/bash

# Exit on error
set -e

# Update package lists
echo "Updating package lists..."
sudo apt-get update -y

# Install zsh and Git if not already installed
echo "Installing zsh and git..."
sudo apt-get install -y zsh git

# Install Oh My Zsh non-interactively
echo "Installing Oh My Zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install zsh-autosuggestions and zsh-syntax-highlighting plugins
echo "Installing zsh plugins..."
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autocomplete
git clone --depth 1 https://github.com/unixorn/fzf-zsh-plugin.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin

# Enable plugins and change theme in ~/.zshrc
echo "Configuring zsh..."
sed -i 's/^plugins=(.*)/plugins=(git cp colored-man-pages colorize zsh-autosuggestions zsh-syntax-highlighting zsh-autocomplete fzf-zsh-plugin)/' ~/.zshrc
sed -i 's/^ZSH_THEME="[^"]*"/ZSH_THEME="agnoster"/' ~/.zshrc

# Set Dotfiles (if applicable)
echo '. ~/bin/dotfiles/bashrc 2>/dev/null' >> ~/.zshrc

# Change default shell to zsh
echo "Changing default shell to zsh..."
sudo usermod --shell $(which zsh) $USER

# Inform user to switch to zsh
echo "To complete the setup, you need to log out and log back in, or restart your terminal."

echo "Installation complete."
